trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm uninstall -g angular-cli
      npm cache clean or npm cache verify #(if npm > 5)
      npm install -g @angular/cli@7.1.4
    displayName: "npm install @angular/cli"

  - script: |
      npm run build-prod
    displayName: "npm build"
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "/src/app/dist/topRateTransfer"
      includeRootFolder: true
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
