trigger:
  - master

pool:
  name: Azure Pipelines

steps:
  - task: NodeTool@0
    displayName: "Use Node 10.x"
    inputs:
      checkLatest: true

  - task: Npm@1
    displayName: "Angular CLI"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm run build-prod"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build-prod"

  - task: Npm@1
    displayName: "Create a deployment build"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build"
    enabled: false

  - task: AzureRmWebAppDeployment@4
    displayName: "Azure App Service Deploy: TopRateTransfer-Frontend"
    inputs:
      azureSubscription: "TopRate-Azure subscription (d36aa739-a744-43e4-aa4b-170a3e8777c7)"
      appType: webAppLinux
      WebAppName: "TopRateTransfer-Frontend"
      packageForLinux: dist/
